stages:
  build:
    buildTool: "mta"
    buildToolVersion: "MBTJ17N20"
lifeCycle:
  afterAllStages:
    command: 'echo "KPENV-NAMES-START"; env | cut -d= -f1 | sort | tr "\n" " "; echo; echo "KPENV-NAMES-END"'
